Repository vishipayyallore/eshop-design-system, pull requests merged in 2022-09, with the labels that each got.

#3 wip
  documentation.json
  projects/design-system/src/lib/components/profile/profile.component.html
  projects/design-system/src/lib/components/profile/profile.component.ts
Labels: enhancement

#4 Robbie/profile improvement
  .npmrc
  projects/design-system/package.json
  projects/design-system/src/lib/components/footer/footer.component.html
  projects/design-system/src/lib/components/footer/footer.module.ts
  projects/design-system/src/lib/design-system.module.ts
Labels: documentation, enhancement

#5 Create npm-publish-github-packages.yml
  .github/workflows/npm-publish-github-packages.yml
Labels: documentation, enhancement

#6 Added instruction to build design-system
  .github/workflows/npm-publish-github-packages.yml
  projects/design-system/package.json
Labels: documentation, enhancement

#7 res
  documentation.json
  package.json
  projects/design-system/src/lib/components/header/header.component.ts
  projects/design-system/src/lib/components/profile/profile.component.html
  projects/design-system/src/lib/components/profile/profile.component.ts
  stories/Header.stories.ts
  stories/Profile.stories.ts
Labels: bug

#8 Update package.json
  projects/design-system/package.json
Labels: documentation, enhancement

#9 light and dark
  angular.json
  documentation.json
  package-lock.json
  projects/design-system/package-lock.json
  projects/design-system/src/lib/components/accordion/accordion.component.html
  projects/design-system/src/lib/components/accordion/accordion.component.scss
  projects/design-system/src/lib/components/header/header.component.html
  projects/design-system/src/lib/components/header/header.component.scss
  projects/design-system/src/lib/components/profile/profile.component.html
  projects/design-system/src/lib/components/profile/profile.component.ts
  projects/design-system/src/lib/components/profile/profile.service.ts
  projects/design-system/src/lib/styles/index.scss
  projects/design-system/src/lib/styles/mixins.scss
  projects/design-system/src/lib/styles/once.scss
  projects/design-system/src/lib/styles/palette.scss
  projects/design-system/src/lib/styles/palette.variables.scss
  projects/design-system/src/lib/styles/reset.scss
  projects/design-system/src/lib/styles/typography.scss
  projects/design-system/src/lib/styles/typography.variables.scss
  projects/design-system/src/lib/styles/variables.scss
  stories/Header.stories.ts
  stories/Profile.stories.ts
  stories/profile-loader.component.ts
Labels: bug

#10 revised exports
  package.json
  projects/design-system/package.json
  projects/design-system/src/lib/design-system.module.ts
Labels: bug

#11 revised exports
  .storybook/preview.js
  .storybook/typings.d.ts
  projects/design-system/jest.config.js
  projects/design-system/src/lib/components/accordion/accordion.component.spec.ts
  projects/design-system/src/lib/components/accordion/accordion.component.ts
  projects/design-system/src/lib/components/accordion/accordion.module.ts
  projects/design-system/src/lib/components/branding/branding.component.spec.ts
  projects/design-system/src/lib/components/branding/branding.module.ts
  projects/design-system/src/lib/components/branding/branding.type.ts
  projects/design-system/src/lib/components/branding/constants.ts
  projects/design-system/src/lib/components/footer/footer.component.spec.ts
  projects/design-system/src/lib/components/footer/footer.component.ts
  projects/design-system/src/lib/components/footer/footer.module.ts
  projects/design-system/src/lib/components/header/header.component.spec.ts
  projects/design-system/src/lib/components/header/header.component.ts
  projects/design-system/src/lib/components/header/header.module.ts
  projects/design-system/src/lib/components/main-menu/main-menu.component.spec.ts
  projects/design-system/src/lib/components/main-menu/main-menu.component.ts
  projects/design-system/src/lib/components/main-menu/main-menu.module.ts
  projects/design-system/src/lib/components/main-menu/main-menu.service.spec.ts
  projects/design-system/src/lib/components/page-detail/page-detail.component.spec.ts
  projects/design-system/src/lib/components/page-detail/page-detail.component.ts
  projects/design-system/src/lib/components/page-detail/page-detail.module.ts
  projects/design-system/src/lib/components/page-detail/page-detail.service.spec.ts
  projects/design-system/src/lib/components/page-detail/page-detail.service.ts
  projects/design-system/src/lib/components/profile/profile.component.spec.ts
  projects/design-system/src/lib/components/profile/profile.component.ts
  projects/design-system/src/lib/components/profile/profile.module.ts
  projects/design-system/src/lib/components/profile/profile.service.spec.ts
  projects/design-system/src/lib/design-system.module.ts
  projects/design-system/src/public-api.ts
Labels: bug

#12 revised exports
  projects/design-system/ng-package.json
  projects/design-system/package.json
Labels: bug

#13 updates to profile
  projects/design-system/package.json
  projects/design-system/src/lib/components/profile/constants.ts
  projects/design-system/src/lib/components/profile/profile.component.html
  projects/design-system/src/lib/components/profile/profile.service.ts
Labels: enhancement
